classDiagram

    class BaseEntity {
        - UUID id
        - LocalDateTime criadoEm

        + BaseEntity()
        + getId() UUID
        + getCriadoEm() LocalDateTime
    }

    class Usuario {
        <<abstract>>
        - String nome
        - String email
        - String senha

        + Usuario(String nome, String email, String senha)
        + autenticar(String senha) Boolean
        + getNome() String
        + getEmail() String
        + getTipoUsuario()* TipoUsuario
    }

    class Vendedor {
        + Vendedor(String nome, String email, String senha)
        + getTipoUsuario() TipoUsuario
    }

    class GerenteVendas {
        + GerenteVendas(String nome, String email, String senha)
        + getTipoUsuario() TipoUsuario
    }

    class Reuniao {
        - String transcricao
        - Duration duracao
        - LocalDateTime ocorreuEm
        - GerenteVendas uploadedBy

        + Reuniao(String transcricao, Duration duracao, LocalDateTime ocorreuEm, GerenteVendas uploadedBy)
        + getTranscricao() String
        + getDuracao() Duration
        + getOcorreuEm() LocalDateTime
        + getUploadedBy() GerenteVendas
        + equals(Object o) boolean
    }

    class AnaliseReuniao {
        - String assunto
        - SentimentoReuniao sentimentoReuniao
        - RiscoCancelamento riscoCancelamento
        - SegmentoCliente segmentoCliente
        - ProdutoTotvs produtoTotvs
        - Reuniao reuniao

        + AnaliseReuniao(Reuniao reuniao)
        + AnaliseReuniao(AnaliseReuniaoDTO analiseReuniaoDTO, Reuniao reuniao)
        + getAssunto() String
        + getSentimentoReuniao() SentimentoReuniao
        + getRiscoCancelamento() RiscoCancelamento
        + getSegmentoCliente() SegmentoCliente
        + getProdutoTotvs() ProdutoTotvs
        + getReuniao() Reuniao
        + equals(Object o) boolean
    }

    class TipoUsuario {
        <<enumeration>>
        VENDEDOR,
        GERENTE_VENDAS
    }

    class SentimentoReuniao {
        <<enumeration>>
        POSITIVO,
        NEUTRO,
        NEGATIVO
    }

    class RiscoCancelamento {
        <<enumeration>>
        MUITO_ALTO,
        ALTO,
        MODERADO,
        BAIXO
    }

    class SegmentoCliente {
        <<enumeration>>
        SAUDE,
        DISTRIBUICAO,
        MANUFATURA,
        SERVICOS,
        CONSTRUCAO_E_PROJETOS,
        EDUCACIONAL,
        AGROINDUSTRIA,
        LOGISTICA,
        SUPERMERCADOS,
        VAREJO,
        NAO_IDENTIFICADO
    }

    class ProdutoTotvs {
        <<enumeration>>
        PROTHEUS,
        RM,
        DATASUL,
        LOGIX,
        RH_CLOCK_IN,
        RH_PERFORMANCE,
        RD_STATION,
        TOTVS_ASSINATURA,
        TOTVS_ANALYTICS,
        FLUIG,
        TOTVS_AUTOMACAO_FISCAL,
        EDUCACAO,
        NAO_IDENTIFICADO
    }

    BaseEntity <|-- Usuario
    BaseEntity <|-- Reuniao

    Usuario <|-- Vendedor
    Usuario <|-- GerenteVendas

    Usuario ..> TipoUsuario

    Reuniao "1" --> "1" GerenteVendas : uploadedBy

    AnaliseReuniao "1" --> "1" Reuniao : reuniao

    AnaliseReuniao ..> SentimentoReuniao
    AnaliseReuniao ..> RiscoCancelamento
    AnaliseReuniao ..> SegmentoCliente
    AnaliseReuniao ..> ProdutoTotvs