CREATE TABLE segmentos_clientes (
    id         NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    nome       VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT pk_segmentos_clientes PRIMARY KEY (id),
    CONSTRAINT uq_segmentos_clientes_nome UNIQUE (nome)
);

CREATE TABLE produtos_totvs (
    id         NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    nome       VARCHAR2(255 CHAR) NOT NULL,
    categoria  VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT pk_produtos_totvs PRIMARY KEY (id),
    CONSTRAINT uq_produtos_totvs_nome UNIQUE (nome)
);

CREATE TABLE reunioes (
    id                  NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    created_at          TIMESTAMP(6),
    updated_at          TIMESTAMP(6),
    transcricao_bruta   CLOB,
    data_reuniao        TIMESTAMP(6),
    duracao             TIMESTAMP(0),
    segmento_cliente_id NUMBER(19, 0),
    CONSTRAINT pk_reunioes PRIMARY KEY (id),
    CONSTRAINT fk_reunioes_segmento_cliente FOREIGN KEY (segmento_cliente_id) REFERENCES segmentos_clientes (id)
);

CREATE TABLE analises_reuniao (
    id                 NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    created_at         TIMESTAMP(6),
    updated_at         TIMESTAMP(6),
    assunto            CLOB NOT NULL,
    sentimento_reuniao VARCHAR2(255 CHAR) NOT NULL,
    risco_cancelamento VARCHAR2(255 CHAR) NOT NULL,
    produto_totvs_id   NUMBER(19, 0) NOT NULL,
    reuniao_id         NUMBER(19, 0) NOT NULL,
    CONSTRAINT pk_analises_reuniao PRIMARY KEY (id),
    CONSTRAINT uq_analises_reuniao_reuniao_id UNIQUE (reuniao_id),
    CONSTRAINT fk_analises_reuniao_produto FOREIGN KEY (produto_totvs_id) REFERENCES produtos_totvs (id),
    CONSTRAINT fk_analises_reuniao_reuniao FOREIGN KEY (reuniao_id) REFERENCES reunioes (id),
    CONSTRAINT ck_analises_reuniao_sentimento CHECK (sentimento_reuniao IN ('POSITIVO', 'NEUTRO', 'NEGATIVO')),
    CONSTRAINT ck_analises_reuniao_risco CHECK (risco_cancelamento IN ('MUITO_ALTO', 'ALTO', 'MODERADO', 'BAIXO'))
);
